# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '461cc182-43ef-4bc5-940c-7485b223e71a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RD-asad'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/SyedAsadRazaDevops/AzureRmPipeline-repo/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName AzureRmPipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'deploypipelineARM'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
